GET https://flickr.com/services/rest/?api_key=d11aa1b5f6d6d8fbdc60f4dc4c589753fcb&format=json&nojsoncallback=1&method=flickr.photos.search&safe_search=1&per_page=5&lat=39.76574&lon=-86.1579024&text=dog